name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest
    strategy:
      matrix:
        destination: ['platform=iOS Simulator,OS=14.5,name=iPhone 12']
        xcode: ['/Applications/Xcode_13.0.app/Contents/Developer']
        
    steps:
    - uses: actions/checkout@v2
    - name: Select Xcode version
      run: sudo xcode-select -s '/Applications/Xcode_13.0.app/Contents/Developer'
    - name: Build
      run: swift build -v
      env:
        DEVELOPER_DIR: ${{ matrix.xcode }}
    - name: Run tests
      run: swift test -v
      env:
        DEVELOPER_DIR: ${{ matrix.xcode }}
